<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- TODO: The model is made in a very simple form, it would be nice to make it a bit better. Is someone willing? -->
    <xacro:macro name="driving_wheel" params="suffix reflect">
        <link name="driving_wheel_${suffix}">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${driving_wheel_diameter/2}" length="${driving_wheel_thickness}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <contact_coefficients mu="100.0" kp="0.0" kd="0.0" />
                <geometry>
                    <cylinder radius="${driving_wheel_diameter/2}" length="${driving_wheel_thickness}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="${driving_wheel_weight}" r="${driving_wheel_diameter/2}" h="${driving_wheel_thickness}" roll="${pi/2}"/>
        </link>

        <joint name="driving_wheel_${suffix}_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="driving_wheel_${suffix}"/>
            <origin xyz="0 ${(plate_radius+driving_wheel_thickness+driving_wheel_base_gap-0.195)/2*reflect} 0.038" rpy="0 0 0"/>
        </joint>

        <gazebo reference="driving_wheel_${suffix}">
            <mu1 value="0.50"/>
            <mu2 value="3.0"/>
            <kp value="10000000.0" />
            <kd value="100.0" />
            <fdir1 value="0 0 1"/>
            <material>Gazebo/Black</material>
        </gazebo>

    </xacro:macro>

</robot>
